backend/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from .views import admin
from .views import user, checkout, checkin,reservation, category, subcategory, dashboard, account
from .views.items import item
from .views.ldap import ldap

urlpatterns = [
    url(r'^$', user.index, name='index'),
    url(r'^login', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout', auth_views.logout, {'next_page': 'login'}, name='logout'),
    #dashboard
    url(r'^dashboard/$', dashboard.show, name='dashboard'),
    url(r'^dashboard/search$', dashboard.search, name='search'),
    #items
    url(r'^item/$', item.list_item_types, name='itemList'),
    url(r'^item/add$', item.add_item_type, name='items'),
    url(r'^item/(?P<item_type_id>\d*)/$', item.show_item_type, name='itemType'),
    url(r'^item/(?P<item_type_id>\d*)/edit$', item.edit_item_type, name='itemEdit'),
    url(r'^item/(?P<item_type_id>\d*)/delete$', item.delete_item_type, name='items'),
    url(r'^item/(?P<item_type_id>\d*)/add$', item.add_item, name='items'),
    url(r'^item/(?P<item_type_id>\d*)/items$', item.list_items, name='items'),
    url(r'^item/(?P<item_type_id>\d*)/(?P<item_id>\d*)$', item.show_item, name='items'),
    url(r'^item/(?P<item_type_id>\d*)/(?P<item_id>\d*)/edit$', item.edit_item, name='items'),
    url(r'^item/(?P<item_id>\d*)/checkout$', checkout.add_item, name='items'),
    #category
    url(r'^category/$', category.list_categories, name='categoryList'),
    url(r'^category/add$', category.add_category, name='categoryAdd'),
    url(r'^category/(?P<category_id>\d*)/$', category.view_category, name='categoryView'),
    url(r'^category/(?P<category_id>\d*)/edit$', category.edit_category, name='categoryEdit'),
    url(r'^category/(?P<category_id>\d*)/subcategory$', subcategory.add_subcategory, name='subcategoryAdd'),
    url(r'^category/(?P<category_id>\d*)/subcategory/(?P<subcategory_id>\d*)$', subcategory.view_subcategory, name='subcategoryView'),
    url(r'^category/(?P<category_id>\d*)/subcategory/(?P<subcategory_id>\d*)/edit$', subcategory.edit_subcategory, name='subcategoryEdit'),
    #user
    url(r'^user/$', user.index, name='items'),
    url(r'^user/staff$', user.get_staff, name='items'),
    url(r'^user/add$', user.index, name='items'),
    url(r'^user/(?P<id>\d*)$', user.index, name='items'),
    url(r'^user/(?P<id>\d*)/edit$', user.index, name='items'),
    url(r'^user/account$', account.show, name='items'),
    url(r'^user/account/password$', account.edit_user, name='items'),
    #search
    url(r'^search$', user.index, name='items'),
    #checkout
    url(r'^checkout/$', checkout.get_pending_checkout, name='items'),
    url(r'^checkout/findUserName/(?P<username>\S*)$', checkout.find_user_name, name='items'),
    url(r'^checkout/findUserID/(?P<uid>\S*)$', checkout.find_user_id, name='items'),
    url(r'^checkout/(?P<checkout_id>\d*)/addUser/(?P<username>\S*)$', checkout.add_user, name='items'),
    url(r'^checkout/addItem/(?P<item_id>\d*)$', checkout.add_item, name='items'),
    url(r'^checkout/removeItem/(?P<item_id>\d*)$', checkout.remove_item, name='items'),
    url(r'^checkout/resetDueDate/(?P<checkoutitem_id>\d*)$', checkout.reset_duedate, name='items'),
    url(r'^checkout/(?P<checkoutitem_id>\d*)/overrideDate$', checkout.override_date, name='items'),
    url(r'^checkout/cart/count', checkout.cart_count, name='items'),
    url(r'^checkout/clear', checkout.clear, name='items'),
    url(r'^checkout/checkSignature', checkout.check_signature, name='items'),
    url(r'^checkout/complete', checkout.complete, name='items'),
   #checkin
    url(r'^checkin/$', checkin.get_open_checkouts, name='items'),
    url(r'^checkin/(?P<checkout_id>\d*)$', checkin.view_checkout, name='items'),
    url(r'^checkin/checkin_item/(?P<checkoutitem_id>\d*)$', checkin.checkin_item, name='items'),
    #reservations
    url(r'^reservationRequest/$', reservation.request, name='reservationRequest'),
    url(r'^reservationRequest/pending$', reservation.view_requests, name='reservationRequestPending'),
    url(r'^reservationRequest/edit/(?P<request_id>\d*)$', reservation.edit_request, name='reservationRequestEdit'),
    url(r'^reservationRequest/decline/(?P<request_id>\d*)$', reservation.decline_request, name='reservationRequestDecline'),
    url(r'^reservation/$', reservation.list_reservations, name='reservationList'),
    #reporting
    url(r'^report_builder/', include('report_builder.urls')),
    url(r'^signatureForm/$', checkout.signature_form, name='signature'),
    url(r'^signatureForm/save/(?P<data_url>\S*)$', checkout.signature_form_save, name='signature'),
    #admin area
    url(r'^admin/$', admin.dashboard, name='reservationList'),
    url(r'^admin/dashboard$', admin.dashboard, name='reservationList'),
    url(r'^admin/user/$', admin.show_users, name='adminUserList'),
    url(r'^admin/user/add$', admin.add_user, name='reservationList'),
    url(r'^admin/user/(?P<user_id>\d*)$', admin.show_user, name='reservationList'),
    url(r'^admin/user/(?P<user_id>\d*)/edit$', admin.edit_user, name='reservationList'),
    url(r'^admin/report/$', admin.dashboard, name='reservationList'),
    url(r'^admin/report/new$', admin.dashboard, name='reservationList'),
    url(r'^admin/report/(?P<id>\d*)$', admin.dashboard, name='reservationList'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seniordev/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^', include('backend.urls')),
]

backend/models.py
from django.db import models
from django.contrib.auth.models import User
from model_utils.models import TimeStampedModel
from model_utils import FieldTracker

#classes with no FKs


class AccessRule(TimeStampedModel):
    name = models.CharField(max_length=100)
    criteria = models.CharField(max_length=200)


class ResponseType(TimeStampedModel):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300)


class ItemState(TimeStampedModel):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)


class ItemCategory(TimeStampedModel):
    categoryDescription = models.CharField(max_length=500)
    categoryName = models.CharField(max_length=100)
    tracker = FieldTracker()

    def __str__(self):
        return self.categoryName

    class ReportBuilder:
        exclude = ('id')
#classes with FKs


class CheckInOrOutListItem(TimeStampedModel):
    prompt = models.CharField(max_length=100)
    responseTypeID = models.ForeignKey(ResponseType, on_delete=models.CASCADE)


class ItemSubCategory(TimeStampedModel):
    itemCategoryID = models.ForeignKey(ItemCategory, on_delete=models.CASCADE)
    subCategoryName = models.CharField(max_length=100)
    subCategoryDescription = models.CharField(max_length=500)
    parentSubCategoryID = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    defaultCheckoutLengthDays = models.IntegerField(default=1, null=True)
    tracker = FieldTracker()

    def __str__(self):
        return self.subCategoryName

    class ReportBuilder:
        exclude = ('id')

class ItemType(TimeStampedModel):
    subCategoryID = models.ForeignKey(ItemSubCategory, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    defaultCheckoutLengthDays = models.IntegerField(default=1, null=True)
    image = models.FileField(upload_to='uploads/itemImages', null= True)
    generalAccessRule = models.ForeignKey(AccessRule, on_delete=models.CASCADE, null=True)
    manufacturer = models.CharField(max_length=100, null=True)
    model = models.CharField(max_length=200, null=True)
    cost = models.DecimalField(decimal_places=2,max_digits=10, null=True)
    needsSignature = models.BooleanField(default=False)
    tracker = FieldTracker()

    def __str__(self):
        return self.name

    class ReportBuilder:
        exclude = ('id')

class Item(TimeStampedModel):
    ItemTypeID = models.ForeignKey(ItemType, on_delete=models.CASCADE)
    serial = models.CharField(max_length=200)
    tag = models.CharField(max_length=200)
    barcode = models.CharField(max_length=200, null= True)
    location = models.CharField(max_length=200)
    itemState = models.ManyToManyField(ItemState, through='ItemStateLog', blank=False)
    checkoutStatus = models.CharField(max_length=50, default="Checked in")
    tracker = FieldTracker()

    class ReportBuilder:
        exclude = ('id')

class ItemStateLog(TimeStampedModel):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    itemState = models.ForeignKey(ItemState, on_delete=models.CASCADE)
    dateTimeChanged = models.DateTimeField()
    changedBy = models.ForeignKey(User, on_delete=models.CASCADE)


class CheckInOrOutList(TimeStampedModel):
    itemCategoryID = models.ForeignKey(ItemCategory, on_delete=models.CASCADE)
    itemSubCategoryID = models.ForeignKey(ItemSubCategory, on_delete=models.CASCADE)
    itemID = models.ForeignKey(Item, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    inOrOut = models.CharField(max_length=3)  # nullable boolean?
    description = models.CharField(max_length=500)
    checkInListItems = models.ManyToManyField(CheckInOrOutListItem, through='CheckInListItems')


class CheckInListItems(TimeStampedModel):
    checkInOrOutList = models.ForeignKey(CheckInOrOutList, on_delete=models.CASCADE)
    checkInOrOutListItem = models.ForeignKey(CheckInOrOutListItem, on_delete=models.CASCADE)
    order = models.IntegerField()


class Checkout(TimeStampedModel):
    person = models.ForeignKey(User, related_name='checkedout_to_person', on_delete=models.CASCADE, null=True)
    dateTimeOut = models.DateTimeField(null=True)
    checkedOutBy = models.ForeignKey(User,related_name='checked_out_by_person', on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=50, default="Pending")
    needsSignature = models.BooleanField(default=False)
    signatureFormFile = models.FileField(max_length=400, null=True, upload_to='uploads/signatures')  # use a file field?
    tracker = FieldTracker()
    #checkInListResults = models.ManyToManyField(CheckInOrOutList, through='CheckInListResults')

    class ReportBuilder:
        exclude = ('id')

class CheckoutItem(TimeStampedModel):
    dateTimeDue = models.DateTimeField(null=True)
    checkout = models.ForeignKey(Checkout, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    dueDateOverridden = models.BooleanField(default=False)
    checkoutPermissionOverridden = models.BooleanField(default=False)
    dateTimeIn = models.DateTimeField(null=True)
    checkedInBy = models.ForeignKey(User,related_name='checked_in_by_person', on_delete=models.CASCADE, null=True)
    tracker = FieldTracker()

    class ReportBuilder:
        exclude = ('id')

class CheckInListResults(TimeStampedModel):
    checkout = models.ForeignKey(Checkout, on_delete=models.CASCADE)
    checkInOrOutListItem = models.ForeignKey(CheckInOrOutListItem)
    response = models.CharField(max_length=100)
    inOrOut = models.CharField(max_length=3)  # nullable boolean?


class ReservationRequest(TimeStampedModel):
    itemSubCategoryID = models.ForeignKey(ItemSubCategory, on_delete=models.CASCADE, db_constraint=False, blank=True, null=True)
    itemTypeID = models.ForeignKey(ItemType, db_constraint=False, blank=True, null=True)
    requester = models.ForeignKey(User, related_name='requested_by', on_delete=models.CASCADE)
    personRequestedFor = models.ForeignKey(User,related_name='requested_for', on_delete=models.CASCADE, blank=True, null=True)
    classRequestedFor = models.CharField(max_length=100,blank=True, null=True)
    startDate = models.DateTimeField()
    endDate = models.DateTimeField()
    lengthOfCheckout = models.IntegerField()
    quantity = models.IntegerField()
    approvedBy = models.ForeignKey(User, related_name='approved_by', null=True, on_delete=models.CASCADE)
    approvedOn = models.DateTimeField(null=True)
    declinedBy = models.ForeignKey(User, related_name='declined_by', null=True, on_delete=models.CASCADE)
    declinedOn = models.DateTimeField(null=True)
    declinedReason = models.CharField(max_length=250,blank=True, null=True)
    tracker = FieldTracker()

    class ReportBuilder:
        exclude = ('id')

class Reservation(TimeStampedModel):
    itemTypeID = models.ForeignKey(ItemType, on_delete=models.CASCADE)
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    startDate = models.DateTimeField()
    endDate = models.DateTimeField()
    lengthOfCheckout = models.IntegerField()
    quantity = models.IntegerField()
    reservationRequestID = models.ForeignKey(ReservationRequest, on_delete=models.CASCADE)
    tracker = FieldTracker()

    class ReportBuilder:
        exclude = ('id')

backend/views/account.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import user_passes_test
from .ldap import ldap
from backend.models import Item, Checkout, CheckoutItem, User
from django.contrib.auth.models import UserManager
from django.contrib.auth.forms import UserChangeForm
from pinax.eventlog.models import log
from django.contrib.auth.decorators import login_required

@login_required
def show(request):
    return render(request, 'account.html', {'title': 'User Account'})


@login_required
def edit_user(request):
    if request.method == "POST":
        user = request.user

        if request.POST['password'] == request.POST['password2'] and user.check_password(request.POST['oldPassword']) and len(request.POST['password']) > 0:
            user.set_password(request.POST['password'])
            user.save()
            return render(request, 'account.html', {'title': 'User Account', 'saved':True})
        else:
            return render(request, 'account.html', {'title': 'User Account', 'saved':False})
        log(
            user=request.user,
            action="USER_MODIFIED",
            obj=user,
            extra={}
        )
    return show(request)

backend/views/admin.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import user_passes_test
from .ldap import ldap
from backend.models import Item, Checkout, CheckoutItem, User
from django.contrib.auth.models import UserManager
from django.contrib.auth.forms import UserChangeForm
from pinax.eventlog.models import log
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt


def admin_check(user):
    # check if user is an admin here
    return user.is_superuser


@user_passes_test(admin_check)
def dashboard(request):
    return render(request, 'admin/dashboard.html', {'title': 'Admin Dashboard'})


@user_passes_test(admin_check)
def show_users(request):
    users = User.objects.all()
    return render(request, 'admin/userList.html', {'title': 'Users | Admin', 'users': users})


@user_passes_test(admin_check)
def show_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    return render(request, 'admin/showUser.html', {'title': user.first_name + ' | Admin', 'user': user})


@csrf_exempt
def add_user(request):
    if request.method == "POST":

        username = request.POST['username']

        ldap_user = ldap.get_user_by_username(username)[0]
        user = User.objects.create_user(username=username, email=ldap.get_email(ldap_user))
        user.first_name = ldap.get_first_name(ldap_user)
        user.last_name = ldap.get_last_name(ldap_user)
        user.save()

        return HttpResponse(status=204)
    else:
        return render(request, 'admin/addUser.html', {'title': 'Add User |'})


@user_passes_test(admin_check)
def edit_user(request, user_id):
    if request.method == "POST":
        user = get_object_or_404(User, pk=user_id)

        if request.POST['user_type'] == "user":
            user.is_staff = False
            user.is_superuser = False
        elif request.POST['user_type'] == "labassistant":
            user.is_staff = True
            user.is_superuser = False
        elif request.POST['user_type'] == "admin":
            user.is_staff = True
            user.is_superuser = True

        if "password" in request.POST:
            if len(request.POST['password']) > 0:
                print("setting password")
                user.set_password(request.POST['password'])
            else:
                print("blank password, not setting")

        user.save()

        log(
            user=request.user,
            action="USER_MODIFIED",
            obj=user,
            extra={}
        )

        return redirect('adminUserList')
    else:
        user = get_object_or_404(User, pk=user_id)
        user_type = ""
        if user.is_staff and user.is_superuser:
            user_type = "admin"
        elif user.is_staff:
            user_type = "labassistant"
        else:
            user_type = "user"

        return render(request, 'admin/editUser.html', {'title': 'Edit User | Admin', 'user': user,'user_type':user_type})

backend/templates/categoryDetailed.html
{% extends 'loggedinbase.html' %}
{% block content %}
{% load widget_tweaks %}
<script>
    $(document).ready(function(){
        $('#itemTable').DataTable();

        $('.viewButton').on('click',function(){
            window.location="/category/{{ category.id }}/subcategory/"+$(this).attr('data-id');
        });

        $('.editButton').on('click',function(){
            window.location="/category/{{ category.id }}/subcategory/"+$(this).attr('data-id') + "/edit";
        });

        $('#addItemButton').on('click',function(){
            window.location="/category/{{ category.id }}/subcategory";
        });
    });


</script>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-6">
            <h3><a href="../category">Categories</a> <i class="fa fa-caret-right" aria-hidden="true"></i> {{ category.categoryName }}</h3>
        </div>
        <div class="col-xs-6 text-right">
            <button id='addItemButton' type="button" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i>  Add New Subcategory</button>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 subCategoryDescription">
            <p><b>Description:</b> {{ category.categoryDescription }}</p>
        </div>  
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <table id="itemTable" class="display">
                <thead>
                    <tr>
                        <th class="text-right">Name</th>
                        <th>Description</th>
                        <th>Default Checkout Length</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for sub in category.itemsubcategory_set.all %}
                        <tr>
                            <td data-id="{{ sub.id }}" class="text-right viewButton"><b>{{ sub.subCategoryName }}</b></td>
                            <td data-id="{{ sub.id }}" class="viewButton"><small>{{ sub.subCategoryDescription }}</small></td>
                            <td data-id="{{ sub.id }}" class="viewButton"><small>{{ sub.defaultCheckoutLengthDays }} days</small></td>
                            <td>
                                <button type="button" data-id="{{ sub.id }}" class="btn btn-primary btn-xs viewButton"><i class="fa fa-eye" aria-hidden="true"></i> View</button>
                                <button type="button" data-id="{{ sub.id }}" class="btn btn-xs editButton"><i class="fa fa-pencil" aria-hidden="true"></i> Edit</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

backend/templates/checkout.html
{% extends 'loggedinbase.html' %}
{% block content %}
{% load widget_tweaks %}
<script>
    var selectUser = function(btn){
        window.location = "/checkout/"+$(btn).attr('data-id')+"/addUser/"+$(btn).attr('username')
      };

    $(document).ready(function() {
        $("#signatureWarning").dialog({
            autoOpen : false, modal : true, show : "blind", hide : "blind"
          });

        $('.selectUserButton').hide();

        $('#uid').focus();

        $('#itemTable').DataTable();

        $('.viewButton').on('click', function () {
            window.location = "/item/" + $(this).attr('data-id');
        });

        $('.removeButton').on('click', function () {
            window.location = "/checkout/removeItem/" + $(this).attr('data-id');
        });

        $('.clearButton').on('click', function () {
            window.location = "/checkout/clear";
        });

        $('.completeButton').on('click', function () {
            window.location = "/checkout/complete";
        });

        $('.resetButton').on('click', function () {
            window.location = "/checkout/resetDueDate/" + $(this).attr('data-id');
        });


        $('.needsSignatureButton').on('click', function () {
            //show dialog
            $("#signatureWarning").dialog("open");
            //window.location = "/checkout/complete";
        });


        $('#userSearchFormUsername').on('submit', function (event) {
            event.preventDefault();
            var username = $('#username').val()
            $.ajax({
                type: "GET",
                url: "/checkout/findUserName/"+username,
                dataType: "json",
                success: function (data) {
                    var userSelect = "<span>Found: </span>";
                    data.users.forEach(function(user){
                        userSelect += '<div><span>'+ user.name +' - '+ user.username +'</span><button onclick="selectUser(this);" type="button" data-id="{{ checkout.id }}" username="'+user.username+'" class="btn btn-primary btn-xs selectUserButton">Select</button></div>';
                    });


                    if(data.users.length == 0){
                        userSelect ="<p>No matching users</p>";
                    }

                    $('#userSelect').html(userSelect);
                },
                error: function () {
                    $('#userSelect').html("<p>No matching users</p>");
                    $('.selectUserButton').hide();
                }
            });
        });

        $('#userSearchFormID').on('submit', function (event) {
            event.preventDefault();
            var uid = $('#uid').val()
            $.ajax({
                type: "GET",
                url: "/checkout/findUserID/"+uid,
                dataType: "json",
                success: function (data) {
                    var userSelect = "<span>Found: </span>";
                    data.users.forEach(function(user){
                        userSelect += '<div><span>'+ user.name +' - '+ user.username +'</span><button onclick="selectUser(this);" type="button" data-id="{{ checkout.id }}" username="'+user.username+'" class="btn btn-primary btn-xs selectUserButton">Select</button></div>';
                    });

                    if(data.users.length == 0){
                        userSelect ="<p>No matching users</p>";
                    }

                    $('#userSelect').html(userSelect);
                },
                error: function () {
                    $('#userSelect').html("<p>No matching users</p>");
                    $('.selectUserButton').hide();
                }
            });
        });

        $('.checkSignature').on('click', function () {
            $.ajax({
                type: "GET",
                url: "/checkout/checkSignature",
                dataType: "json",
                success: function (data) {
                    if(data.ready){
                        $('#signatureResult').html('<img style="max-width:100%;" src="'+ data.url +'" />');
                        document.getElementById("dialogComplete").disabled = false;
                    }else{
                        $('#signatureResult').html("<p>No signature yet</p>");
                    }
                },
                error: function () {
                    $('#signatureResult').html("<p>No signature yet</p>");
                }
            });
        })
    });


</script>


<div class="container-fluid tableHeader">
    <div class="row">
        <div class="col-xs-4">
            <h3>Check Out </h3>
        </div>
        <div class="col-xs-8">
            <div class="row">
                <div class="col-sm-4 text-right">
                    
                </div>

                <div class="col-sm-8 text-left">

                    <form id="userSearchFormUsername" class="form-group input-group">
                          {% csrf_token %}
                          <input placeholder="Search by RIT Username" class="form-control" type="text" size="15" required name="username" id="username">
                          <span class="input-group-btn">
                             <input class="btn" type="submit" value="Search">
                          </span>
                    </form>
                    <form id="userSearchFormID" class="form-group input-group">
                          {% csrf_token %}
                          <input placeholder="Search by UID" class="form-control" type="password" size="15" required name="uid" id="uid">
                          <span class="input-group-btn">
                            <input class="btn" type="submit" value="Search">
                          </span>
                    </form>
                    <div class="row">
                        <div id="userSelect"></div>
                    </div>

                    <div class="row">
                        <div class="col-xs-9 text-right">
                            <b>Checkout To:</b>
                        </div>
                        <div class="col-xs-3 text-left">
                                {{ checkout.person }}
                        </div>
                        <div class="col-xs-9 text-right">
                            <b>Status:</b>
                        </div>
                        <div class="col-xs-3 text-left">
                            {% if checkout.status == 'Open' %}
                                <span class="btn btn-success btn-xs"><i class="fa fa-check" aria-hidden="true"></i> {{ checkout.status }}</span>
                            {% elif checkout.status == 'Closed' %}
                                <span class="btn btn-danger btn-xs"><i class="fa fa-times" aria-hidden="true"></i> {{ checkout.status }}</span>
                            {% elif checkout.status == 'Checked in' %}
                                <span class="btn btn-success btn-xs"><i class="fa fa-check" aria-hidden="true"></i> {{ checkout.status }}</span>
                            {% elif checkout.status == 'Checked out' %}
                                <span class="btn btn-danger btn-xs"><i class="fa fa-times" aria-hidden="true"></i> {{ checkout.status }}</span>
                            {% elif checkout.status == 'Pending' %}
                                <span class="btn btn-warning btn-xs"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> {{ checkout.status }}</span>
                            {% else %}
                                <span class="btn btn-info btn-xs">{{ checkout.status }}</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <table id="itemTable" class="display">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Manufacturer</th>
                        <th>Model</th>
                        <th>Tags</th>
                        <th>Location</th>
                        <th>Signature?</th>
                        <th>Checkout Status</th>
                        <th>Due Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for checkoutitem in checkout.checkoutitem_set.all %}
                        <tr>
                            <td>{{ checkoutitem.item.ItemTypeID.name }}</td>
                            <td>{{ checkoutitem.item.ItemTypeID.manufacturer }}</td>
                            <td>{{ checkoutitem.item.ItemTypeID.model }}</td>
                            <td>{{ checkoutitem.item.tag }}</td>
                            <td>{{ checkoutitem.item.location }}</td>
                            <td>{{ checkoutitem.item.ItemTypeID.needsSignature }}</td>
                            <td>{{ checkoutitem.item.checkoutStatus }}</td>
                            <td>{{ checkoutitem.dateTimeDue }}</td>
                            <td>
                                <form action="/checkout/{{ checkoutitem.id }}/overrideDate" class="form-signin" method="post">
                                    {% csrf_token %}
                                    <input type="datetime" name="overrideDate" placeholder="YYYY-MM-DD HH:MM">
                                    <button type="submit" class="save btn btn-default">Save</button>
                                </form>
                                <button type="button" data-id="{{ checkoutitem.id }}" class="btn btn-primary btn-xs resetButton">Reset Due Date</button>
                                <button type="button" data-id="{{ checkoutitem.item.id }}" class="btn btn-primary btn-xs removeButton">Remove</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6">
            <button type="button" data-id="{{ checkout.id }}" class="btn clearButton"><i class="fa fa-ban" aria-hidden="true"></i> Remove All Items</button>
        </div>
        <div class="col-xs-6 text-right">
            {%  if checkout.needsSignature %}
                <button type="button" data-id="{{ checkout.id }}" class="btn btn-success needsSignatureButton"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Check Out All Items - Needs Signature</button>
            {% else %}
                <button type="button" data-id="{{ checkout.id }}" class="btn btn-success completeButton"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Check Out All Items</button>
            {% endif %}
        </div>
    </div>


    <div id="signatureWarning" title="Signature Required">
        <p>Signature is required.</p>
        <p>Please give present the tablet.</p>

        <div id = "signatureResult"></div>

        <button type="button" class="btn btn-success checkSignature" ><i class="fa fa-shopping-cart" aria-hidden="true"></i> Check for Signature</button>
        <button type="button" id = "dialogComplete" data-id="{{ checkout.id }}" class="btn btn-success completeButton" disabled="true"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Check Out All Items</button>
    </div>

</div>
{% endblock %}